from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
from PyQt5 import uic

from selections import Selections
from crossover import Crossovers
from mutation import Mutations
import cv2
from genetic_algorithm import ReproductionData, ImageReproduction

class Ui_MainWindow_triangles(object):

    def openWindow_main(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_main()
        self.ui.setupUi(self.window)
        self.window.show()

    def importImage(self):
        importedFile = QFileDialog.getOpenFileName()
        self.filePath = importedFile[0]
        print(self.filePath)

    def enableBittonStartAlg(self):
        selectionMethod = list([self.checkBox_rank.isChecked(), self.checkBox_roulette.isChecked(), self.checkBox_tournament.isChecked()])
        crossoverMethod = list([self.checkBox_single_point.isChecked(), self.checkBox_two_point.isChecked(), self.checkBox_uniform.isChecked()])
        mutationMethod = [self.checkBox_replacment.isChecked(), self.checkBox_random_swap.isChecked(), self.checkBox_adjacent_swap.isChecked()]

        if True in selectionMethod and True in crossoverMethod and True in mutationMethod and self.filePath != None:
            self.pushButton_start_algorithm.setEnabled(True)
    def startAlgorithm(self):
        selectionMethod = list([self.checkBox_rank.isChecked(), self.checkBox_roulette.isChecked(), self.checkBox_tournament.isChecked()])
        selectionMethodLamb = list([Selections.rank, Selections.roulette_wheel, Selections.tournament])
        selectionMethodInput = list([selectionMethodLamb[id] for i, id in enumerate(selectionMethod) if i])

        crossoverMethod = list([self.checkBox_single_point.isChecked(), self.checkBox_two_point.isChecked(), self.checkBox_uniform.isChecked()])
        crossoverMethodLamb = list([Crossovers.single_point, Crossovers.two_point, Crossovers.uniform])
        crossoverMethodInput = list([crossoverMethodLamb[id] for i, id in enumerate(crossoverMethod) if i])

        mutationMethod = [self.checkBox_replacment.isChecked(), self.checkBox_random_swap.isChecked(), self.checkBox_adjacent_swap.isChecked()]
        mutationMethodLamb = list([Mutations.replacement, Mutations.random_swap, Mutations.adjacent_swap])
        mutationMethodInput = list([mutationMethodLamb[id] for i, id in enumerate(mutationMethod) if i])

        if not(True in selectionMethod and True in crossoverMethod and True in mutationMethod):
            message = QMessageBox()
            message.setText("Verify methods")
            message.exec_()
        else:
            numOfGen = int(self.lineEdit_num_gen.text())
            mutPercent = float(self.lineEdit_mut_percent.text())
            numOfParents = int(self.lineEdit_num_parents.text())
            numOfOffsprings = int(self.lineEdit_num_offsprings.text())
            epsajlon = float(self.lineEdit_epsilon.text())
            iterTermination = int(self.lineEdit_term_iterations.text())
            n_points = int(self.lineEdit_n_points.text())
            enableTriangulation = True
            
            img = cv2.imread(self.filePath)

            pixelsReproductionParams = ReproductionData(img, numOfGen, selectionMethodInput, crossoverMethodInput,
                                                    mutationMethodInput, numOfParents, numOfOffsprings,
                                                    mutPercent, epsajlon, iterTermination, enableTriangulation, n_points)

            pixelsReproduction = ImageReproduction(pixelsReproductionParams)
            reproduced_image = pixelsReproduction.reproduce_image()

            cv2.imwrite('reproduced_image.jpg', reproduced_image)
            cv2.imshow("reproduced_image", reproduced_image)

    def setupUi(self, MainWindow_triangles):
        self.filePath = None
        MainWindow_triangles.setObjectName("MainWindow_triangles")
        MainWindow_triangles.resize(796, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow_triangles)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_return_to_menu = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.openWindow_main())
        self.pushButton_return_to_menu.clicked.connect(MainWindow_triangles.close)
        self.pushButton_return_to_menu.setGeometry(QtCore.QRect(720, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_return_to_menu.setFont(font)
        self.pushButton_return_to_menu.setObjectName("pushButton_return_to_menu")
        self.label_crossover = QtWidgets.QLabel(self.centralwidget)
        self.label_crossover.setGeometry(QtCore.QRect(270, 40, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_crossover.setFont(font)
        self.label_crossover.setObjectName("label_crossover")
        self.checkBox_uniform = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_uniform.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_uniform.setGeometry(QtCore.QRect(270, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_uniform.setFont(font)
        self.checkBox_uniform.setObjectName("checkBox_uniform")
        self.checkBox_adjacent_swap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_adjacent_swap.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_adjacent_swap.setGeometry(QtCore.QRect(500, 170, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_adjacent_swap.setFont(font)
        self.checkBox_adjacent_swap.setObjectName("checkBox_adjacent_swap")
        self.label_selection = QtWidgets.QLabel(self.centralwidget)
        self.label_selection.setGeometry(QtCore.QRect(50, 40, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection.setFont(font)
        self.label_selection.setObjectName("label_selection")
        self.checkBox_single_point = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_single_point.setChecked(True)
        self.checkBox_single_point.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_single_point.setGeometry(QtCore.QRect(270, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_single_point.setFont(font)
        self.checkBox_single_point.setObjectName("checkBox_single_point")
        self.checkBox_two_point = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_two_point.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_two_point.setGeometry(QtCore.QRect(270, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_two_point.setFont(font)
        self.checkBox_two_point.setObjectName("checkBox_two_point")
        self.checkBox_replacment = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_replacment.setChecked(True)
        self.checkBox_replacment.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_replacment.setGeometry(QtCore.QRect(500, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_replacment.setFont(font)
        self.checkBox_replacment.setObjectName("checkBox_replacment")
        self.checkBox_random_swap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_random_swap.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_random_swap.setGeometry(QtCore.QRect(500, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_random_swap.setFont(font)
        self.checkBox_random_swap.setObjectName("checkBox_random_swap")
        self.checkBox_rank = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rank.setChecked(True)
        self.checkBox_rank.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_rank.setGeometry(QtCore.QRect(50, 130, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_rank.setFont(font)
        self.checkBox_rank.setObjectName("checkBox_rank")
        self.checkBox_tournament = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_tournament.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_tournament.setGeometry(QtCore.QRect(50, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_tournament.setFont(font)
        self.checkBox_tournament.setObjectName("checkBox_tournament")
        self.checkBox_roulette = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_roulette.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_roulette.setGeometry(QtCore.QRect(50, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_roulette.setFont(font)
        self.checkBox_roulette.setObjectName("checkBox_roulette")
        self.label_mutation = QtWidgets.QLabel(self.centralwidget)
        self.label_mutation.setGeometry(QtCore.QRect(500, 40, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_mutation.setFont(font)
        self.label_mutation.setObjectName("label_mutation")
        self.label_num_offsprings = QtWidgets.QLabel(self.centralwidget)
        self.label_num_offsprings.setGeometry(QtCore.QRect(40, 390, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_num_offsprings.setFont(font)
        self.label_num_offsprings.setObjectName("label_num_offsprings")
        self.label_iterations_termination = QtWidgets.QLabel(self.centralwidget)
        self.label_iterations_termination.setGeometry(QtCore.QRect(40, 510, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_iterations_termination.setFont(font)
        self.label_iterations_termination.setObjectName("label_iterations_termination")
        self.label_mutation_percentage = QtWidgets.QLabel(self.centralwidget)
        self.label_mutation_percentage.setGeometry(QtCore.QRect(40, 310, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mutation_percentage.setFont(font)
        self.label_mutation_percentage.setObjectName("label_mutation_percentage")
        self.label_term_cond = QtWidgets.QLabel(self.centralwidget)
        self.label_term_cond.setGeometry(QtCore.QRect(30, 420, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_term_cond.setFont(font)
        self.label_term_cond.setObjectName("label_term_cond")
        self.lineEdit_epsilon = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_epsilon.setGeometry(QtCore.QRect(120, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_epsilon.setFont(font)
        self.lineEdit_epsilon.setClearButtonEnabled(False)
        self.lineEdit_epsilon.setObjectName("lineEdit_epsilon")
        self.label_epsajlon = QtWidgets.QLabel(self.centralwidget)
        self.label_epsajlon.setGeometry(QtCore.QRect(40, 470, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_epsajlon.setFont(font)
        self.label_epsajlon.setObjectName("label_epsajlon")
        self.lineEdit_num_gen = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_gen.setGeometry(QtCore.QRect(220, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_gen.setFont(font)
        self.lineEdit_num_gen.setObjectName("lineEdit_num_gen")
        self.label_num_parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_num_parameters.setGeometry(QtCore.QRect(40, 350, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_num_parameters.setFont(font)
        self.label_num_parameters.setObjectName("label_num_parameters")
        self.lineEdit_num_offsprings = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_offsprings.setGeometry(QtCore.QRect(220, 380, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_offsprings.setFont(font)
        self.lineEdit_num_offsprings.setObjectName("lineEdit_num_offsprings")
        self.label_num_iter = QtWidgets.QLabel(self.centralwidget)
        self.label_num_iter.setGeometry(QtCore.QRect(40, 270, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_num_iter.setFont(font)
        self.label_num_iter.setObjectName("label_num_iter")
        self.lineEdit_term_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_term_iterations.setGeometry(QtCore.QRect(120, 500, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_term_iterations.setFont(font)
        self.lineEdit_term_iterations.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_term_iterations.setObjectName("lineEdit_term_iterations")
        self.lineEdit_mut_percent = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mut_percent.setGeometry(QtCore.QRect(220, 300, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_mut_percent.setFont(font)
        self.lineEdit_mut_percent.setObjectName("lineEdit_mut_percent")
        self.lineEdit_num_parents = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_parents.setGeometry(QtCore.QRect(220, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_parents.setFont(font)
        self.lineEdit_num_parents.setObjectName("lineEdit_num_parents")
        self.label_alg_param = QtWidgets.QLabel(self.centralwidget)
        self.label_alg_param.setGeometry(QtCore.QRect(30, 220, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_alg_param.setFont(font)
        self.label_alg_param.setObjectName("label_alg_param")
        # self.pushButton_import_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_import_image = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.importImage())
        self.pushButton_import_image.clicked.connect(self.enableBittonStartAlg)
        self.pushButton_import_image.setGeometry(QtCore.QRect(580, 350, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_import_image.setFont(font)
        self.pushButton_import_image.setObjectName("pushButton_import_image")
        # self.pushButton_start_algorithm = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_algorithm = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.startAlgorithm())
        self.pushButton_start_algorithm.setEnabled(False)
        self.pushButton_start_algorithm.setGeometry(QtCore.QRect(510, 440, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start_algorithm.setFont(font)
        self.pushButton_start_algorithm.setObjectName("pushButton_start_algorithm")
        self.label_n_points = QtWidgets.QLabel(self.centralwidget)
        self.label_n_points.setGeometry(QtCore.QRect(600, 210, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_n_points.setFont(font)
        self.label_n_points.setObjectName("label_n_points")
        self.label_n_points_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_n_points_2.setGeometry(QtCore.QRect(590, 240, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_n_points_2.setFont(font)
        self.label_n_points_2.setObjectName("label_n_points_2")
        self.lineEdit_n_points = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_n_points.setGeometry(QtCore.QRect(610, 290, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_n_points.setFont(font)
        self.lineEdit_n_points.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_n_points.setObjectName("lineEdit_n_points")
        MainWindow_triangles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_triangles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_triangles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_triangles)
        self.statusbar.setObjectName("statusbar")
        MainWindow_triangles.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow_triangles)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_triangles)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_triangles)

    def retranslateUi(self, MainWindow_triangles):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_triangles.setWindowTitle(_translate("MainWindow_triangles", "TRIANGLES"))
        self.pushButton_return_to_menu.setText(_translate("MainWindow_triangles", "Menu"))
        self.label_crossover.setText(_translate("MainWindow_triangles", "Crossover method:"))
        self.checkBox_uniform.setText(_translate("MainWindow_triangles", "uniform"))
        self.checkBox_adjacent_swap.setText(_translate("MainWindow_triangles", "adjacent swap"))
        self.label_selection.setText(_translate("MainWindow_triangles", "Selection method:"))
        self.checkBox_single_point.setText(_translate("MainWindow_triangles", "single point"))
        self.checkBox_two_point.setText(_translate("MainWindow_triangles", "two point"))
        self.checkBox_replacment.setText(_translate("MainWindow_triangles", "replacement"))
        self.checkBox_random_swap.setText(_translate("MainWindow_triangles", "random swap"))
        self.checkBox_rank.setText(_translate("MainWindow_triangles", "rank"))
        self.checkBox_tournament.setText(_translate("MainWindow_triangles", "tournament"))
        self.checkBox_roulette.setText(_translate("MainWindow_triangles", "roulette wheel"))
        self.label_mutation.setText(_translate("MainWindow_triangles", "Mutation method:"))
        self.label_num_offsprings.setText(_translate("MainWindow_triangles", "number of offsprings:"))
        self.label_iterations_termination.setText(_translate("MainWindow_triangles", "iterations:"))
        self.label_mutation_percentage.setText(_translate("MainWindow_triangles", "mutation percentage:"))
        self.label_term_cond.setText(_translate("MainWindow_triangles", "Termination conditions:"))
        self.lineEdit_epsilon.setText(_translate("MainWindow_triangles", "1e-12"))
        self.lineEdit_epsilon.setPlaceholderText(_translate("MainWindow_triangles", "1e-12"))
        self.label_epsajlon.setText(_translate("MainWindow_triangles", "epsilon:"))
        self.lineEdit_num_gen.setText(_translate("MainWindow_triangles", "10000"))
        self.lineEdit_num_gen.setPlaceholderText(_translate("MainWindow_triangles", "10000"))
        self.label_num_parameters.setText(_translate("MainWindow_triangles", "number of parents:"))
        self.lineEdit_num_offsprings.setText(_translate("MainWindow_triangles", "8"))
        self.lineEdit_num_offsprings.setPlaceholderText(_translate("MainWindow_triangles", "8"))
        self.label_num_iter.setText(_translate("MainWindow_triangles", "number of generation: "))
        self.lineEdit_term_iterations.setText(_translate("MainWindow_triangles", "500"))
        self.lineEdit_term_iterations.setPlaceholderText(_translate("MainWindow_triangles", "500"))
        self.lineEdit_mut_percent.setText(_translate("MainWindow_triangles", "0.01"))
        self.lineEdit_mut_percent.setPlaceholderText(_translate("MainWindow_triangles", "0.01"))
        self.lineEdit_num_parents.setText(_translate("MainWindow_triangles", "4"))
        self.lineEdit_num_parents.setPlaceholderText(_translate("MainWindow_triangles", "4"))
        self.label_alg_param.setText(_translate("MainWindow_triangles", "Algorithm parameters:"))
        self.pushButton_import_image.setText(_translate("MainWindow_triangles", "Import image"))
        self.pushButton_start_algorithm.setText(_translate("MainWindow_triangles", "Start algorithm"))
        self.label_n_points.setText(_translate("MainWindow_triangles", "Number of points"))
        self.label_n_points_2.setText(_translate("MainWindow_triangles", "to generate triangles"))
        self.lineEdit_n_points.setText(_translate("MainWindow_triangles", "1200"))
        self.lineEdit_n_points.setPlaceholderText(_translate("MainWindow_triangles", "1200"))
        self.menuFile.setTitle(_translate("MainWindow_triangles", "File"))
        self.actionClose.setText(_translate("MainWindow_triangles", "Close"))

class Ui_MainWindow_pixels(object):
    def openWindow_main(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_main()
        self.ui.setupUi(self.window)
        self.window.show()

    # def updateProgressBar(self, value):
    #     self.progressBar.setValue(value)

    def importImage(self):
        importedFile = QFileDialog.getOpenFileName()
        self.filePath = importedFile[0]
        print(self.filePath)

    def enableBittonStartAlg(self):
        selectionMethod = list([self.checkBox_rank.isChecked(), self.checkBox_roulette.isChecked(), self.checkBox_tournament.isChecked()])
        crossoverMethod = list([self.checkBox_single_point.isChecked(), self.checkBox_two_point.isChecked(), self.checkBox_uniform.isChecked()])
        mutationMethod = [self.checkBox_replacment.isChecked(), self.checkBox_random_swap.isChecked(), self.checkBox_adjacent_swap.isChecked()]

        if True in selectionMethod and True in crossoverMethod and True in mutationMethod and self.filePath != None:
            self.pushButton_start_algorithm.setEnabled(True)
    def startAlgorithm(self):
        selectionMethod = list([self.checkBox_rank.isChecked(), self.checkBox_roulette.isChecked(), self.checkBox_tournament.isChecked()])
        selectionMethodLamb = list([Selections.rank, Selections.roulette_wheel, Selections.tournament])
        selectionMethodInput = list([selectionMethodLamb[id] for i, id in enumerate(selectionMethod) if i])

        crossoverMethod = list([self.checkBox_single_point.isChecked(), self.checkBox_two_point.isChecked(), self.checkBox_uniform.isChecked()])
        crossoverMethodLamb = list([Crossovers.single_point, Crossovers.two_point, Crossovers.uniform])
        crossoverMethodInput = list([crossoverMethodLamb[id] for i, id in enumerate(crossoverMethod) if i])

        mutationMethod = [self.checkBox_replacment.isChecked(), self.checkBox_random_swap.isChecked(), self.checkBox_adjacent_swap.isChecked()]
        mutationMethodLamb = list([Mutations.replacement, Mutations.random_swap, Mutations.adjacent_swap])
        mutationMethodInput = list([mutationMethodLamb[id] for i, id in enumerate(mutationMethod) if i])

        if not(True in selectionMethod and True in crossoverMethod and True in mutationMethod):
            message = QMessageBox()
            message.setText("Verify methods")
            message.exec_()
        else:
            numOfGen = int(self.lineEdit_num_gen.text())
            mutPercent = float(self.lineEdit_mut_percent.text())
            numOfParents = int(self.lineEdit_num_parents.text())
            numOfOffsprings = int(self.lineEdit_num_offsprings.text())
            epsajlon = float(self.lineEdit_epsilon.text())
            iterTermination = int(self.lineEdit_term_iterations.text())
            enableTriangulation = False
            n_points = 1800

            # self.progressBar.setMinimum(0)
            # self.progressBar.setMaximum(numOfGen)

            img = cv2.imread(self.filePath)

            pixelsReproductionParams = ReproductionData(img, numOfGen, selectionMethodInput, crossoverMethodInput,
                                                    mutationMethodInput, numOfParents, numOfOffsprings,
                                                    mutPercent, epsajlon, iterTermination, enableTriangulation, n_points)

            pixelsReproduction = ImageReproduction(pixelsReproductionParams)
            reproduced_image = pixelsReproduction.reproduce_image()

            cv2.imwrite('reproduced_image.jpg', reproduced_image)
            cv2.imshow("reproduced_image", reproduced_image)

    def setupUi(self, MainWindow_pixels):
        self.filePath = None
        MainWindow_pixels.setObjectName("MainWindow_pixels")
        MainWindow_pixels.resize(774, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow_pixels)
        self.centralwidget.setObjectName("centralwidget")
        self.label_selection = QtWidgets.QLabel(self.centralwidget)
        self.label_selection.setGeometry(QtCore.QRect(70, 20, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection.setFont(font)
        self.label_selection.setObjectName("label_selection")
        self.label_crossover = QtWidgets.QLabel(self.centralwidget)
        self.label_crossover.setGeometry(QtCore.QRect(290, 20, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_crossover.setFont(font)
        self.label_crossover.setObjectName("label_crossover")
        self.label_mutation = QtWidgets.QLabel(self.centralwidget)
        self.label_mutation.setGeometry(QtCore.QRect(520, 20, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_mutation.setFont(font)
        self.label_mutation.setObjectName("label_mutation")
        self.checkBox_roulette = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_roulette.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_roulette.setGeometry(QtCore.QRect(70, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_roulette.setFont(font)
        self.checkBox_roulette.setObjectName("checkBox_roulette")
        self.checkBox_rank = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rank.setChecked(True)
        self.checkBox_rank.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_rank.setGeometry(QtCore.QRect(70, 110, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_rank.setFont(font)
        self.checkBox_rank.setObjectName("checkBox_rank")
        self.checkBox_tournament = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_tournament.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_tournament.setGeometry(QtCore.QRect(70, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_tournament.setFont(font)
        self.checkBox_tournament.setObjectName("checkBox_tournament")
        self.checkBox_single_point = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_single_point.setChecked(True)
        self.checkBox_single_point.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_single_point.setGeometry(QtCore.QRect(290, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_single_point.setFont(font)
        self.checkBox_single_point.setObjectName("checkBox_single_point")
        self.checkBox_uniform = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_uniform.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_uniform.setGeometry(QtCore.QRect(290, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_uniform.setFont(font)
        self.checkBox_uniform.setObjectName("checkBox_uniform")
        self.checkBox_two_point = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_two_point.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_two_point.setGeometry(QtCore.QRect(290, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_two_point.setFont(font)
        self.checkBox_two_point.setObjectName("checkBox_two_point")
        self.checkBox_replacment = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_replacment.setChecked(True)
        self.checkBox_replacment.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_replacment.setGeometry(QtCore.QRect(520, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_replacment.setFont(font)
        self.checkBox_replacment.setObjectName("checkBox_replacment")
        self.checkBox_adjacent_swap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_adjacent_swap.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_adjacent_swap.setGeometry(QtCore.QRect(520, 150, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_adjacent_swap.setFont(font)
        self.checkBox_adjacent_swap.setObjectName("checkBox_adjacent_swap")
        self.checkBox_random_swap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_random_swap.clicked.connect(self.enableBittonStartAlg)
        self.checkBox_random_swap.setGeometry(QtCore.QRect(520, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_random_swap.setFont(font)
        self.checkBox_random_swap.setObjectName("checkBox_random_swap")
        self.label_selection_alg_param = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_alg_param.setGeometry(QtCore.QRect(20, 220, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_alg_param.setFont(font)
        self.label_selection_alg_param.setObjectName("label_selection_alg_param")
        self.label_num_iter = QtWidgets.QLabel(self.centralwidget)
        self.label_num_iter.setGeometry(QtCore.QRect(30, 270, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_num_iter.setFont(font)
        self.label_num_iter.setObjectName("label_num_iter")
        self.label_mutation_percentage = QtWidgets.QLabel(self.centralwidget)
        self.label_mutation_percentage.setGeometry(QtCore.QRect(30, 310, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mutation_percentage.setFont(font)
        self.label_mutation_percentage.setObjectName("label_mutation_percentage")
        self.label_num_parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_num_parameters.setGeometry(QtCore.QRect(30, 350, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_num_parameters.setFont(font)
        self.label_num_parameters.setObjectName("label_num_parameters")
        self.label_num_offsprings = QtWidgets.QLabel(self.centralwidget)
        self.label_num_offsprings.setGeometry(QtCore.QRect(30, 390, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_num_offsprings.setFont(font)
        self.label_num_offsprings.setObjectName("label_num_offsprings")
        self.label_epsajlon = QtWidgets.QLabel(self.centralwidget)
        self.label_epsajlon.setGeometry(QtCore.QRect(30, 470, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_epsajlon.setFont(font)
        self.label_epsajlon.setObjectName("label_epsajlon")
        self.label_iterations_termination = QtWidgets.QLabel(self.centralwidget)
        self.label_iterations_termination.setGeometry(QtCore.QRect(30, 510, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_iterations_termination.setFont(font)
        self.label_iterations_termination.setObjectName("label_iterations_termination")
        self.label_selection_term_cond = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_term_cond.setGeometry(QtCore.QRect(30, 420, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_term_cond.setFont(font)
        self.label_selection_term_cond.setObjectName("label_selection_term_cond")
        self.pushButton_import_image = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.importImage())
        self.pushButton_import_image.clicked.connect(self.enableBittonStartAlg)
        self.pushButton_import_image.setGeometry(QtCore.QRect(570, 250, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_import_image.setFont(font)
        self.pushButton_import_image.setObjectName("pushButton_import_image")
        self.pushButton_start_algorithm = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.startAlgorithm())
        self.pushButton_start_algorithm.setGeometry(QtCore.QRect(500, 340, 261, 81))
        self.pushButton_start_algorithm.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start_algorithm.setFont(font)
        self.pushButton_start_algorithm.setObjectName("pushButton_start_algorithm")
        self.lineEdit_num_gen = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_gen.setGeometry(QtCore.QRect(210, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_gen.setFont(font)
        self.lineEdit_num_gen.setObjectName("lineEdit_num_gen")
        self.lineEdit_mut_percent = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mut_percent.setGeometry(QtCore.QRect(210, 300, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_mut_percent.setFont(font)
        self.lineEdit_mut_percent.setObjectName("lineEdit_mut_percent")
        self.lineEdit_num_parents = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_parents.setGeometry(QtCore.QRect(210, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_parents.setFont(font)
        self.lineEdit_num_parents.setObjectName("lineEdit_num_parents")
        self.lineEdit_num_offsprings = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_offsprings.setGeometry(QtCore.QRect(210, 380, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_offsprings.setFont(font)
        self.lineEdit_num_offsprings.setObjectName("lineEdit_num_offsprings")
        self.lineEdit_epsilon = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_epsilon.setGeometry(QtCore.QRect(110, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_epsilon.setFont(font)
        self.lineEdit_epsilon.setClearButtonEnabled(False)
        self.lineEdit_epsilon.setObjectName("lineEdit_epsilon")
        self.lineEdit_term_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_term_iterations.setGeometry(QtCore.QRect(110, 500, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_term_iterations.setFont(font)
        self.lineEdit_term_iterations.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_term_iterations.setObjectName("lineEdit_term_iterations")
        # self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        # self.progressBar.setGeometry(QtCore.QRect(400, 500, 361, 31))
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # self.progressBar.setFont(font)
        # self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.progressBar.setProperty("value", 0)
        # self.progressBar.setObjectName("progressBar")
        self.pushButton_return_to_menu = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.openWindow_main())
        self.pushButton_return_to_menu.clicked.connect(MainWindow_pixels.close)
        self.pushButton_return_to_menu.setGeometry(QtCore.QRect(700, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_return_to_menu.setFont(font)
        self.pushButton_return_to_menu.setObjectName("pushButton_return_to_menu")
        MainWindow_pixels.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_pixels)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_pixels.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_pixels)
        self.statusbar.setObjectName("statusbar")
        MainWindow_pixels.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow_pixels)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_pixels)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_pixels)

    def retranslateUi(self, MainWindow_pixels):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_pixels.setWindowTitle(_translate("MainWindow_pixels", "PIXELS"))
        self.label_selection.setText(_translate("MainWindow_pixels", "Selection method:"))
        self.label_crossover.setText(_translate("MainWindow_pixels", "Crossover method:"))
        self.label_mutation.setText(_translate("MainWindow_pixels", "Mutation method:"))
        self.checkBox_roulette.setText(_translate("MainWindow_pixels", "roulette wheel"))
        self.checkBox_rank.setText(_translate("MainWindow_pixels", "rank"))
        self.checkBox_tournament.setText(_translate("MainWindow_pixels", "tournament"))
        self.checkBox_single_point.setText(_translate("MainWindow_pixels", "single point"))
        self.checkBox_uniform.setText(_translate("MainWindow_pixels", "uniform"))
        self.checkBox_two_point.setText(_translate("MainWindow_pixels", "two point"))
        self.checkBox_replacment.setText(_translate("MainWindow_pixels", "replacement"))
        self.checkBox_adjacent_swap.setText(_translate("MainWindow_pixels", "adjacent swap"))
        self.checkBox_random_swap.setText(_translate("MainWindow_pixels", "random swap"))
        self.label_selection_alg_param.setText(_translate("MainWindow_pixels", "Algorithm parameters:"))
        self.label_num_iter.setText(_translate("MainWindow_pixels", "number of generation: "))
        self.label_mutation_percentage.setText(_translate("MainWindow_pixels", "mutation percentage:"))
        self.label_num_parameters.setText(_translate("MainWindow_pixels", "number of parents:"))
        self.label_num_offsprings.setText(_translate("MainWindow_pixels", "number of offsprings:"))
        self.label_epsajlon.setText(_translate("MainWindow_pixels", "epsilon:"))
        self.label_iterations_termination.setText(_translate("MainWindow_pixels", "iterations:"))
        self.label_selection_term_cond.setText(_translate("MainWindow_pixels", "Termination conditions:"))
        self.pushButton_import_image.setText(_translate("MainWindow_pixels", "Import image"))
        self.pushButton_start_algorithm.setText(_translate("MainWindow_pixels", "Start algorithm"))
        self.lineEdit_num_gen.setText(_translate("MainWindow_pixels", "10000"))
        self.lineEdit_num_gen.setPlaceholderText(_translate("MainWindow_pixels", "10000"))
        self.lineEdit_mut_percent.setText(_translate("MainWindow_pixels", "0.01"))
        self.lineEdit_mut_percent.setPlaceholderText(_translate("MainWindow_pixels", "0.01"))
        self.lineEdit_num_parents.setText(_translate("MainWindow_pixels", "4"))
        self.lineEdit_num_parents.setPlaceholderText(_translate("MainWindow_pixels", "4"))
        self.lineEdit_num_offsprings.setText(_translate("MainWindow_pixels", "8"))
        self.lineEdit_num_offsprings.setPlaceholderText(_translate("MainWindow_pixels", "8"))
        self.lineEdit_epsilon.setText(_translate("MainWindow_pixels", "1e-12"))
        self.lineEdit_epsilon.setPlaceholderText(_translate("MainWindow_pixels", "1e-12"))
        self.lineEdit_term_iterations.setText(_translate("MainWindow_pixels", "500"))
        self.lineEdit_term_iterations.setPlaceholderText(_translate("MainWindow_pixels", "500"))
        self.pushButton_return_to_menu.setText(_translate("MainWindow_pixels", "Menu"))
        self.menuFile.setTitle(_translate("MainWindow_pixels", "File"))
        self.actionClose.setText(_translate("MainWindow_pixels", "Close"))

class Ui_MainWindow_main(object):
    def openWindow_pixels(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_pixels()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindow_triangles(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_triangles()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow_main):
        MainWindow_main.setObjectName("MainWindow_main")
        MainWindow_main.resize(390, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow_main)
        self.centralwidget.setObjectName("centralwidget")
        self.label_selection_GA = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_GA.setGeometry(QtCore.QRect(90, 20, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_GA.setFont(font)
        self.label_selection_GA.setObjectName("label_selection_GA")
        self.label_selection_image_repr = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_image_repr.setGeometry(QtCore.QRect(40, 70, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_image_repr.setFont(font)
        self.label_selection_image_repr.setObjectName("label_selection_image_repr")
        self.label_selection_image_repro = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_image_repro.setGeometry(QtCore.QRect(100, 160, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_image_repro.setFont(font)
        self.label_selection_image_repro.setObjectName("label_selection_image_repro")
        self.pushButton_pixels = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.openWindow_pixels())
        self.pushButton_pixels.clicked.connect(MainWindow_main.close)
        self.pushButton_pixels.setGeometry(QtCore.QRect(100, 220, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_pixels.setFont(font)
        self.pushButton_pixels.setObjectName("pushButton_pixels")
        self.pushButton_triangles = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openWindow_triangles())
        self.pushButton_triangles.clicked.connect(MainWindow_main.close)
        self.pushButton_triangles.setGeometry(QtCore.QRect(100, 310, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_triangles.setFont(font)
        self.pushButton_triangles.setObjectName("pushButton_triangles")
        MainWindow_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_main.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow_main)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_main)

    def retranslateUi(self, MainWindow_main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_main.setWindowTitle(_translate("MainWindow_main", "ImageReproductionGA"))
        self.label_selection_GA.setText(_translate("MainWindow_main", "Genetic Algorithm"))
        self.label_selection_image_repr.setText(_translate("MainWindow_main", "Image Reproduction"))
        self.label_selection_image_repro.setText(_translate("MainWindow_main", "Choose method:"))
        self.pushButton_pixels.setText(_translate("MainWindow_main", "PIXELS"))
        self.pushButton_triangles.setText(_translate("MainWindow_main", "TRIANGLES"))
        self.menuFile.setTitle(_translate("MainWindow_main", "File"))
        self.actionClose.setText(_translate("MainWindow_main", "Close"))

def run_gui():
    app = QtWidgets.QApplication([])
    MainWindow_main = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_main()
    ui.setupUi(MainWindow_main)
    MainWindow_main.show()
    app.exec_()

run_gui()