# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pixels_window import Ui_MainWindow_pixels
from triangles_window import Ui_MainWindow_triangles

class Ui_MainWindow_main(object):
    def openWindow_pixels(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_pixels()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindow_triangles(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_triangles()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow_main):
        MainWindow_main.setObjectName("MainWindow_main")
        MainWindow_main.resize(390, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow_main)
        self.centralwidget.setObjectName("centralwidget")
        self.label_selection_GA = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_GA.setGeometry(QtCore.QRect(90, 20, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_GA.setFont(font)
        self.label_selection_GA.setObjectName("label_selection_GA")
        self.label_selection_image_repr = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_image_repr.setGeometry(QtCore.QRect(40, 70, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_image_repr.setFont(font)
        self.label_selection_image_repr.setObjectName("label_selection_image_repr")
        self.label_selection_image_repro = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_image_repro.setGeometry(QtCore.QRect(100, 160, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_image_repro.setFont(font)
        self.label_selection_image_repro.setObjectName("label_selection_image_repro")
        self.pushButton_pixels = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.openWindow_pixels())
        self.pushButton_pixels.clicked.connect(MainWindow_main.close)
        self.pushButton_pixels.setGeometry(QtCore.QRect(100, 220, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_pixels.setFont(font)
        self.pushButton_pixels.setObjectName("pushButton_pixels")
        self.pushButton_triangles = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openWindow_triangles())
        self.pushButton_triangles.clicked.connect(MainWindow_main.close)
        self.pushButton_triangles.setGeometry(QtCore.QRect(100, 310, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_triangles.setFont(font)
        self.pushButton_triangles.setObjectName("pushButton_triangles")
        MainWindow_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_main.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow_main)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_main)

    def retranslateUi(self, MainWindow_main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_main.setWindowTitle(_translate("MainWindow_main", "ImageReproductionGA"))
        self.label_selection_GA.setText(_translate("MainWindow_main", "Genetic Algorithm"))
        self.label_selection_image_repr.setText(_translate("MainWindow_main", "Image Reproduction"))
        self.label_selection_image_repro.setText(_translate("MainWindow_main", "Choose method:"))
        self.pushButton_pixels.setText(_translate("MainWindow_main", "PIXELS"))
        self.pushButton_triangles.setText(_translate("MainWindow_main", "TRIANGLES"))
        self.menuFile.setTitle(_translate("MainWindow_main", "File"))
        self.actionClose.setText(_translate("MainWindow_main", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_main = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_main()
    ui.setupUi(MainWindow_main)
    MainWindow_main.show()
    sys.exit(app.exec_())
