# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'triangles_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_triangles(object):

    def openWindow_main(self):
        from main_window import Ui_MainWindow_main
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_main()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow_triangles):
        MainWindow_triangles.setObjectName("MainWindow_triangles")
        MainWindow_triangles.resize(732, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow_triangles)
        self.centralwidget.setObjectName("centralwidget")
        self.label_selection_triangles = QtWidgets.QLabel(self.centralwidget)
        self.label_selection_triangles.setGeometry(QtCore.QRect(290, 50, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_selection_triangles.setFont(font)
        self.label_selection_triangles.setObjectName("label_selection_triangles")
        self.pushButton_return_to_menu = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda: self.openWindow_main())
        self.pushButton_return_to_menu.clicked.connect(MainWindow_triangles.close)
        self.pushButton_return_to_menu.setGeometry(QtCore.QRect(660, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_return_to_menu.setFont(font)
        self.pushButton_return_to_menu.setObjectName("pushButton_return_to_menu")
        MainWindow_triangles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_triangles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_triangles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_triangles)
        self.statusbar.setObjectName("statusbar")
        MainWindow_triangles.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow_triangles)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_triangles)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_triangles)

    def retranslateUi(self, MainWindow_triangles):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_triangles.setWindowTitle(_translate("MainWindow_triangles", "TRIANGLES"))
        self.label_selection_triangles.setText(_translate("MainWindow_triangles", "Triangles"))
        self.pushButton_return_to_menu.setText(_translate("MainWindow_triangles", "Menu"))
        self.menuFile.setTitle(_translate("MainWindow_triangles", "File"))
        self.actionClose.setText(_translate("MainWindow_triangles", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_triangles = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_triangles()
    ui.setupUi(MainWindow_triangles)
    MainWindow_triangles.show()
    sys.exit(app.exec_())
